# Generated by Django 5.0.6 on 2024-07-07 19:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('bus_stop_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'bus_stop',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('end_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('distance', models.FloatField()),
                ('cost', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'route',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BusOption',
            fields=[
                ('bus_option_id', models.AutoField(primary_key=True, serialize=False)),
                ('fare', models.CharField(max_length=50)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_stops.route')),
            ],
            options={
                'db_table': 'bus_option',
                'managed': True,
            },
        ),
    ]
