# Generated by Django 5.0.6 on 2024-06-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_stops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busstop',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='busstop',
            table='BusStop',
        ),
    ]
