# Generated by Django 5.0.6 on 2024-07-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_stops', '0002_remove_route_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='busoption',
            name='bus_option_name',
            field=models.CharField(default='no_name', max_length=500),
            preserve_default=False,
        ),
    ]
